var dir_51add06cfe42de42d15d5e915d9d31fa =
[
    [ "imgui", "dir_2d2f17b9aaec143a61f4f5a76310f53a.html", "dir_2d2f17b9aaec143a61f4f5a76310f53a" ],
    [ "w_attributes.hpp", "w__attributes_8hpp.html", "w__attributes_8hpp" ],
    [ "w_color.hpp", "w__color_8hpp.html", "w__color_8hpp" ],
    [ "w_command.hpp", "util_2w__command_8hpp.html", "util_2w__command_8hpp" ],
    [ "w_dialogs.hpp", "w__dialogs_8hpp.html", "w__dialogs_8hpp" ],
    [ "w_discord_rpc.hpp", "w__discord__rpc_8hpp.html", null ],
    [ "w_filewatcher.hpp", "w__filewatcher_8hpp.html", "w__filewatcher_8hpp" ],
    [ "w_gamepadcodes.hpp", "w__gamepadcodes_8hpp.html", "w__gamepadcodes_8hpp" ],
    [ "w_keycodes.hpp", "w__keycodes_8hpp.html", "w__keycodes_8hpp" ],
    [ "w_label_texture.hpp", "w__label__texture_8hpp.html", "w__label__texture_8hpp" ],
    [ "w_logger.hpp", "w__logger_8hpp.html", "w__logger_8hpp" ],
    [ "w_math.hpp", "w__math_8hpp.html", "w__math_8hpp" ],
    [ "w_mousecodes.hpp", "w__mousecodes_8hpp.html", "w__mousecodes_8hpp" ],
    [ "w_natural_sort.hpp", "w__natural__sort_8hpp.html", "w__natural__sort_8hpp" ],
    [ "w_platform.hpp", "w__platform_8hpp.html", "w__platform_8hpp" ],
    [ "w_platformdetection.hpp", "w__platformdetection_8hpp.html", null ],
    [ "w_spirv.hpp", "w__spirv_8hpp.html", "w__spirv_8hpp" ],
    [ "w_thread_pool.hpp", "w__thread__pool_8hpp.html", "w__thread__pool_8hpp" ],
    [ "w_tracy.hpp", "w__tracy_8hpp.html", "w__tracy_8hpp" ],
    [ "w_utils.hpp", "w__utils_8hpp.html", "w__utils_8hpp" ],
    [ "w_uuid.hpp", "w__uuid_8hpp.html", "w__uuid_8hpp" ],
    [ "w_vectors.hpp", "w__vectors_8hpp.html", "w__vectors_8hpp" ],
    [ "w_vfs.hpp", "w__vfs_8hpp.html", "w__vfs_8hpp" ]
];