var dir_07800c8bc9e485b30bf8571db4a636e5 =
[
    [ "ui", "dir_76d0ef40f76d608420c48278aed0e92d.html", "dir_76d0ef40f76d608420c48278aed0e92d" ],
    [ "w_anim_clip_editor.h", "w__anim__clip__editor_8h.html", "w__anim__clip__editor_8h" ],
    [ "w_anim_controller_editor.h", "w__anim__controller__editor_8h.html", "w__anim__controller__editor_8h" ],
    [ "w_anim_graph_delegate.h", "w__anim__graph__delegate_8h.html", "w__anim__graph__delegate_8h" ],
    [ "w_asset_browser_panel.h", "w__asset__browser__panel_8h.html", "w__asset__browser__panel_8h" ],
    [ "w_command_palette.h", "w__command__palette_8h.html", "w__command__palette_8h" ],
    [ "w_csharp_lang.h", "w__csharp__lang_8h.html", "w__csharp__lang_8h" ],
    [ "w_editor.h", "w__editor_8h.html", "w__editor_8h" ],
    [ "w_editor_asset_factory.h", "w__editor__asset__factory_8h.html", "w__editor__asset__factory_8h" ],
    [ "w_editor_asset_ui.h", "w__editor__asset__ui_8h.html", "w__editor__asset__ui_8h" ],
    [ "w_editor_components.h", "w__editor__components_8h.html", "w__editor__components_8h" ],
    [ "w_editor_entity_factory.h", "w__editor__entity__factory_8h.html", "w__editor__entity__factory_8h" ],
    [ "w_editor_icons.h", "w__editor__icons_8h.html", "w__editor__icons_8h" ],
    [ "w_editor_input_ui.h", "w__editor__input__ui_8h.html", "w__editor__input__ui_8h" ],
    [ "w_editor_name_prompt.h", "w__editor__name__prompt_8h.html", "w__editor__name__prompt_8h" ],
    [ "w_icon_font_loader.h", "w__icon__font__loader_8h.html", "w__icon__font__loader_8h" ],
    [ "w_icon_source.h", "w__icon__source_8h.html", "w__icon__source_8h" ],
    [ "w_lsp_autocomplete.h", "w__lsp__autocomplete_8h.html", "w__lsp__autocomplete_8h" ],
    [ "w_lsp_client.h", "w__lsp__client_8h.html", "w__lsp__client_8h" ],
    [ "w_node_graph_editor.h", "w__node__graph__editor_8h.html", "w__node__graph__editor_8h" ],
    [ "w_notifications.h", "w__notifications_8h.html", "w__notifications_8h" ],
    [ "w_project.h", "w__project_8h.html", "w__project_8h" ],
    [ "w_project_loader.h", "w__project__loader_8h.html", "w__project__loader_8h" ],
    [ "w_rml_lang.h", "w__rml__lang_8h.html", "w__rml__lang_8h" ],
    [ "w_thumbnail_cache.h", "w__thumbnail__cache_8h.html", "w__thumbnail__cache_8h" ],
    [ "w_undo.h", "w__undo_8h.html", "w__undo_8h" ],
    [ "w_undo_helpers.h", "w__undo__helpers_8h.html", "w__undo__helpers_8h" ],
    [ "w_vfs_browser.h", "w__vfs__browser_8h.html", "w__vfs__browser_8h" ]
];