var hierarchy =
[
    [ "Wiesel::Application", "classWiesel_1_1Application.html", null ],
    [ "Wiesel::AppWindow", "classWiesel_1_1AppWindow.html", [
      [ "Wiesel::GlfwAppWindow", "classWiesel_1_1GlfwAppWindow.html", null ]
    ] ],
    [ "Wiesel::AttachmentTexture", "classWiesel_1_1AttachmentTexture.html", null ],
    [ "Wiesel::AttachmentTextureInfo", "structWiesel_1_1AttachmentTextureInfo.html", null ],
    [ "Wiesel::AttachmentTextureProps", "structWiesel_1_1AttachmentTextureProps.html", null ],
    [ "Wiesel::DescriptorSetLayout::Binding", "structWiesel_1_1DescriptorSetLayout_1_1Binding.html", null ],
    [ "Wiesel::CameraComponent", "structWiesel_1_1CameraComponent.html", null ],
    [ "Wiesel::CameraData", "structWiesel_1_1CameraData.html", null ],
    [ "Wiesel::CameraUniformData", "structWiesel_1_1CameraUniformData.html", null ],
    [ "Wiesel::CanvasComponent", "structWiesel_1_1CanvasComponent.html", null ],
    [ "Wiesel::CanvasSystem", "classWiesel_1_1CanvasSystem.html", null ],
    [ "Wiesel::Cascade", "structWiesel_1_1Cascade.html", null ],
    [ "Wiesel::ChangeResult< N >", "structWiesel_1_1ChangeResult.html", null ],
    [ "Wiesel::Color< V >", "structWiesel_1_1Color.html", null ],
    [ "Wiesel::Color< float >", "structWiesel_1_1Color.html", null ],
    [ "Wiesel::CommandBuffer", "classWiesel_1_1CommandBuffer.html", null ],
    [ "Wiesel::CommandPool", "classWiesel_1_1CommandPool.html", null ],
    [ "Wiesel::DescriptorSet", "classWiesel_1_1DescriptorSet.html", null ],
    [ "Wiesel::DescriptorSetLayout", "classWiesel_1_1DescriptorSetLayout.html", null ],
    [ "Wiesel::Engine", "classWiesel_1_1Engine.html", null ],
    [ "Wiesel::Entity", "classWiesel_1_1Entity.html", null ],
    [ "Wiesel::Event", "classWiesel_1_1Event.html", [
      [ "Wiesel::AppRecreateSwapChainsEvent", "classWiesel_1_1AppRecreateSwapChainsEvent.html", null ],
      [ "Wiesel::KeyEvent", "classWiesel_1_1KeyEvent.html", [
        [ "Wiesel::KeyPressedEvent", "classWiesel_1_1KeyPressedEvent.html", null ],
        [ "Wiesel::KeyReleasedEvent", "classWiesel_1_1KeyReleasedEvent.html", null ],
        [ "Wiesel::KeyTypedEvent", "classWiesel_1_1KeyTypedEvent.html", null ]
      ] ],
      [ "Wiesel::MouseButtonEvent", "classWiesel_1_1MouseButtonEvent.html", [
        [ "Wiesel::MouseButtonPressedEvent", "classWiesel_1_1MouseButtonPressedEvent.html", null ],
        [ "Wiesel::MouseButtonReleasedEvent", "classWiesel_1_1MouseButtonReleasedEvent.html", null ]
      ] ],
      [ "Wiesel::MouseMovedEvent", "classWiesel_1_1MouseMovedEvent.html", null ],
      [ "Wiesel::MouseScrolledEvent", "classWiesel_1_1MouseScrolledEvent.html", null ],
      [ "Wiesel::ScriptsReloadedEvent", "classWiesel_1_1ScriptsReloadedEvent.html", null ],
      [ "Wiesel::WindowCloseEvent", "classWiesel_1_1WindowCloseEvent.html", null ],
      [ "Wiesel::WindowResizeEvent", "classWiesel_1_1WindowResizeEvent.html", null ]
    ] ],
    [ "Wiesel::EventDispatcher", "classWiesel_1_1EventDispatcher.html", null ],
    [ "Wiesel::EventHandlerComponent", "structWiesel_1_1EventHandlerComponent.html", null ],
    [ "Wiesel::FieldData", "classWiesel_1_1FieldData.html", null ],
    [ "Wiesel::Dialogs::FilterEntry", "structWiesel_1_1Dialogs_1_1FilterEntry.html", null ],
    [ "Wiesel::Font", "classWiesel_1_1Font.html", null ],
    [ "Wiesel::Framebuffer", "classWiesel_1_1Framebuffer.html", null ],
    [ "Wiesel::FrustumPlanes", "structWiesel_1_1FrustumPlanes.html", null ],
    [ "Wiesel::IBehavior", "classWiesel_1_1IBehavior.html", [
      [ "Wiesel::MonoBehavior", "classWiesel_1_1MonoBehavior.html", null ]
    ] ],
    [ "Wiesel::IComponent", "structWiesel_1_1IComponent.html", [
      [ "Wiesel::BehaviorsComponent", "classWiesel_1_1BehaviorsComponent.html", null ],
      [ "Wiesel::IdComponent", "structWiesel_1_1IdComponent.html", null ],
      [ "Wiesel::ModelComponent", "structWiesel_1_1ModelComponent.html", null ],
      [ "Wiesel::RectangleTransformComponent", "structWiesel_1_1RectangleTransformComponent.html", null ],
      [ "Wiesel::TagComponent", "structWiesel_1_1TagComponent.html", null ],
      [ "Wiesel::TransformComponent", "structWiesel_1_1TransformComponent.html", null ],
      [ "Wiesel::TreeComponent", "structWiesel_1_1TreeComponent.html", null ]
    ] ],
    [ "Wiesel::ImageView", "classWiesel_1_1ImageView.html", null ],
    [ "Wiesel::InputManager", "classWiesel_1_1InputManager.html", null ],
    [ "Wiesel::KeyData", "structWiesel_1_1KeyData.html", null ],
    [ "Wiesel::Layer", "classWiesel_1_1Layer.html", [
      [ "Wiesel::Editor::EditorOverlay", "classWiesel_1_1Editor_1_1EditorOverlay.html", null ],
      [ "Wiesel::ImGuiLayer", "classWiesel_1_1ImGuiLayer.html", null ]
    ] ],
    [ "Wiesel::LightBase", "structWiesel_1_1LightBase.html", null ],
    [ "Wiesel::LightDirect", "structWiesel_1_1LightDirect.html", null ],
    [ "Wiesel::LightDirectComponent", "structWiesel_1_1LightDirectComponent.html", null ],
    [ "Wiesel::LightPoint", "structWiesel_1_1LightPoint.html", null ],
    [ "Wiesel::LightPointComponent", "structWiesel_1_1LightPointComponent.html", null ],
    [ "Wiesel::LightsUniformData", "structWiesel_1_1LightsUniformData.html", null ],
    [ "Wiesel::Material", "structWiesel_1_1Material.html", null ],
    [ "Wiesel::MatricesUniformData", "structWiesel_1_1MatricesUniformData.html", null ],
    [ "Wiesel::MemoryBuffer", "classWiesel_1_1MemoryBuffer.html", [
      [ "Wiesel::IndexBuffer", "classWiesel_1_1IndexBuffer.html", null ],
      [ "Wiesel::UniformBuffer", "classWiesel_1_1UniformBuffer.html", null ]
    ] ],
    [ "Wiesel::Mesh", "structWiesel_1_1Mesh.html", null ],
    [ "Wiesel::Model", "structWiesel_1_1Model.html", null ],
    [ "MonoObjectWrapper", "classMonoObjectWrapper.html", null ],
    [ "MonoStringWrapper", "classMonoStringWrapper.html", null ],
    [ "Wiesel::Pipeline", "structWiesel_1_1Pipeline.html", null ],
    [ "Wiesel::PipelineProperties", "structWiesel_1_1PipelineProperties.html", null ],
    [ "Wiesel::ProfileData", "structWiesel_1_1ProfileData.html", null ],
    [ "Wiesel::Profiler", "classWiesel_1_1Profiler.html", null ],
    [ "Wiesel::ProfilerInstance", "classWiesel_1_1ProfilerInstance.html", null ],
    [ "Wiesel::PushConstant", "structWiesel_1_1PushConstant.html", null ],
    [ "Wiesel::QueueFamilyIndices", "structWiesel_1_1QueueFamilyIndices.html", null ],
    [ "Wiesel::Renderer", "classWiesel_1_1Renderer.html", null ],
    [ "Wiesel::RendererProperties", "structWiesel_1_1RendererProperties.html", null ],
    [ "Wiesel::RenderPass", "classWiesel_1_1RenderPass.html", null ],
    [ "Wiesel::Sampler", "classWiesel_1_1Sampler.html", null ],
    [ "Wiesel::SamplerProps", "structWiesel_1_1SamplerProps.html", null ],
    [ "Wiesel::Scene", "classWiesel_1_1Scene.html", null ],
    [ "ScopedMonoStringWrapper", "classScopedMonoStringWrapper.html", null ],
    [ "Wiesel::ScriptData", "classWiesel_1_1ScriptData.html", null ],
    [ "Wiesel::ScriptInstance", "classWiesel_1_1ScriptInstance.html", null ],
    [ "Wiesel::ScriptManager", "classWiesel_1_1ScriptManager.html", null ],
    [ "Wiesel::ScriptManagerProperties", "structWiesel_1_1ScriptManagerProperties.html", null ],
    [ "Wiesel::Shader", "structWiesel_1_1Shader.html", null ],
    [ "Wiesel::Pipeline::ShaderInfo", "structWiesel_1_1Pipeline_1_1ShaderInfo.html", null ],
    [ "Wiesel::ShaderProperties", "structWiesel_1_1ShaderProperties.html", null ],
    [ "Wiesel::ShadowMapMatricesUniformData", "structWiesel_1_1ShadowMapMatricesUniformData.html", null ],
    [ "Wiesel::ShadowPipelinePushConstant", "structWiesel_1_1ShadowPipelinePushConstant.html", null ],
    [ "Wiesel::Skybox", "classWiesel_1_1Skybox.html", null ],
    [ "Wiesel::Pipeline::SpecializationData", "structWiesel_1_1Pipeline_1_1SpecializationData.html", null ],
    [ "Wiesel::SpriteAsset", "classWiesel_1_1SpriteAsset.html", null ],
    [ "Wiesel::SpriteBuilder", "classWiesel_1_1SpriteBuilder.html", null ],
    [ "Wiesel::SpriteComponent", "classWiesel_1_1SpriteComponent.html", null ],
    [ "Wiesel::SpriteTexture", "structWiesel_1_1SpriteTexture.html", null ],
    [ "Wiesel::SpriteUniformData", "structWiesel_1_1SpriteUniformData.html", null ],
    [ "Wiesel::SSAOKernelUniformData", "structWiesel_1_1SSAOKernelUniformData.html", null ],
    [ "Wiesel::SSAOSpecializationData", "structWiesel_1_1SSAOSpecializationData.html", null ],
    [ "Wiesel::SwapChainSupportDetails", "structWiesel_1_1SwapChainSupportDetails.html", null ],
    [ "Wiesel::TextComponent", "structWiesel_1_1TextComponent.html", null ],
    [ "Wiesel::Texture", "classWiesel_1_1Texture.html", null ],
    [ "Wiesel::TextureProps", "structWiesel_1_1TextureProps.html", null ],
    [ "Wiesel::Time", "classWiesel_1_1Time.html", null ],
    [ "Wiesel::UUID", "classWiesel_1_1UUID.html", null ],
    [ "Wiesel::Vector3", "classWiesel_1_1Vector3.html", null ],
    [ "Wiesel::Vertex2DNoColor", "structWiesel_1_1Vertex2DNoColor.html", null ],
    [ "Wiesel::Vertex3D", "structWiesel_1_1Vertex3D.html", null ],
    [ "Wiesel::VertexSprite", "structWiesel_1_1VertexSprite.html", null ],
    [ "Wiesel::WindowProperties", "structWiesel_1_1WindowProperties.html", null ],
    [ "Wiesel::WindowSize", "structWiesel_1_1WindowSize.html", null ]
];