//
//   Copyright 2026 Metehan Gezer
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//

#include "generator.h"

#include <sstream>

namespace wiesel::code_gen {

static std::string FieldToDisplayName(const std::string& field_name) {
  std::string name = field_name;
  while (!name.empty() && name.back() == '_') {
    name.pop_back();
  }
  return name;
}

std::string GenerateReflection(const ParseResult& parse_result,
                               const std::string& original_include_path) {
  std::ostringstream out;

  out << "// AUTO-GENERATED by wiesel-codegen - DO NOT EDIT\n";
  out << "// entt/meta and core/w_reflect.h must be included before this "
         "file.\n";
  out << "#pragma once\n\n";
  out << "#include \"" << original_include_path << "\"\n\n";
  out << "namespace wiesel::generated {\n\n";

  for (const auto& cls : parse_result.classes) {
    std::string func_name = "Reflect" + cls.short_name;
    out << "inline void " << func_name << "() {\n";
    out << "  using namespace entt::literals;\n";
    out << "  entt::meta_factory<" << cls.qualified_name << ">{}\n";
    out << "      .type(\"" << cls.short_name << "\"_hs)";

    for (const auto& field : cls.fields) {
      std::string display_name = FieldToDisplayName(field.field_name);
      std::string member_ptr =
          "&" + cls.qualified_name + "::" + field.field_name;

      out << "\n      .data<" << member_ptr << ">(\"" << display_name
          << "\"_hs)";
      out << "\n          .custom<WPropertyMeta>(WPropertyMeta{"
          << "\n              .display_name = \"" << display_name << "\","
          << "\n              .field_name = \"" << field.field_name << "\","
          << "\n              .type_name = \"" << field.type_name << "\","
          << "\n              .serializable = "
          << (HasAttribute(field.attributes, PropertyAttribute::Serializable)
                  ? "true"
                  : "false")
          << ","
          << "\n              .animatable = "
          << (HasAttribute(field.attributes, PropertyAttribute::Animatable)
                  ? "true"
                  : "false")
          << ","
          << "\n              .read_only = "
          << (HasAttribute(field.attributes, PropertyAttribute::ReadOnly)
                  ? "true"
                  : "false")
          << "})";
    }

    out << ";\n";
    out << "}\n\n";
  }

  out << "}  // namespace wiesel::generated\n";
  return out.str();
}

std::string GenerateReflectAll(
    const std::vector<std::string>& generated_includes,
    const std::vector<std::string>& function_names) {
  std::ostringstream out;

  out << "// AUTO-GENERATED by wiesel-codegen - DO NOT EDIT\n";
  out << "#pragma once\n\n";

  for (const auto& inc : generated_includes) {
    out << "#include \"" << inc << "\"\n";
  }

  out << "\nnamespace wiesel::generated {\n\n";
  out << "inline void ReflectAll() {\n";

  for (const auto& fn : function_names) {
    out << "  " << fn << "();\n";
  }

  out << "}\n\n";
  out << "}  // namespace wiesel::generated\n";
  return out.str();
}

}  // namespace wiesel::code_gen
